import Link from 'next/link';
import type { Metadata } from 'next';
import { prisma } from '@/lib/db';
import { Sparkles, ArrowRight, CalendarDays } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Blog — ShipList',
  description: 'In-depth articles about the products launched on ShipList, generated by AI and published for every Premium+ maker.',
};

export const revalidate = 60;

export default async function BlogIndexPage() {
  let posts: Array<{
    id: string;
    slug: string;
    title: string;
    content: string;
    createdAt: Date;
    product: { name: string; slug: string; logo: string | null; tagline: string } | null;
  }> = [];

  try {
    posts = await prisma.blogPost.findMany({
      orderBy: { createdAt: 'desc' },
      include: {
        product: { select: { name: true, slug: true, logo: true, tagline: true } },
      },
    });
  } catch {
    // DB not connected yet — show empty state
  }

  return (
    <div className="container max-w-4xl mx-auto px-4 py-16">
      <div className="flex items-center gap-2 text-sm text-primary font-semibold uppercase tracking-wider mb-4">
        <Sparkles className="h-4 w-4" />
        AI-Generated Articles
      </div>
      <h1 className="text-4xl font-extrabold tracking-tight mb-4">ShipList Blog</h1>
      <p className="text-muted-foreground text-lg mb-12 max-w-xl">
        Deep-dive articles about products launched on ShipList. Each article is AI-written as part of our Premium+ tier.
      </p>

      {posts.length === 0 ? (
        <div className="text-center py-20 bg-card border border-border/50 rounded-3xl">
          <Sparkles className="h-10 w-10 text-muted-foreground/30 mx-auto mb-4" />
          <h2 className="text-xl font-bold mb-2">No articles yet</h2>
          <p className="text-muted-foreground text-sm mb-6 max-w-xs mx-auto">
            Articles are auto-published when a maker upgrades to Premium+. Be the first!
          </p>
          <Link
            href="/pricing"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-primary text-primary-foreground font-bold hover:bg-primary/90 transition-colors"
          >
            See pricing <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      ) : (
        <div className="space-y-6">
          {posts.map((post) => (
            <Link
              key={post.id}
              href={`/blog/${post.slug}`}
              className="group block bg-card border border-border/50 rounded-2xl p-6 hover:border-border hover:shadow-md transition-all"
            >
              <div className="flex items-start gap-4">
                {post.product?.logo && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={post.product.logo}
                    alt={post.product.name}
                    className="w-12 h-12 rounded-xl object-cover border border-border/50 flex-shrink-0"
                  />
                )}
                <div className="min-w-0 flex-1">
                  <h2 className="font-bold text-lg mb-1 group-hover:text-primary transition-colors line-clamp-2">
                    {post.title}
                  </h2>
                  <p className="text-sm text-muted-foreground line-clamp-2 mb-3">
                    {post.content.replace(/[#*>`\[\]]/g, '').substring(0, 180)}…
                  </p>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <CalendarDays className="h-3.5 w-3.5" />
                      {new Date(post.createdAt).toLocaleDateString('en-US', {
                        year: 'numeric', month: 'short', day: 'numeric',
                      })}
                    </span>
                    {post.product && (
                      <span className="text-primary font-medium">{post.product.name}</span>
                    )}
                  </div>
                </div>
                <ArrowRight className="h-5 w-5 text-muted-foreground group-hover:text-primary group-hover:translate-x-1 transition-all flex-shrink-0 mt-1" />
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
